# Voter Enrollment

## Import Libraries and Data

In [15]:
# import libraries
import pandas as pd
import csv
import json
import geopandas as gpd

In [16]:
## set display settings
pd.options.display.max_rows = 500

In [18]:
## read in voter registration files from november 2025
bronx_voters_25 = pd.read_excel('../input/voter_enrollment/bronxed_feb25.xlsx')
staten_voters_25 = pd.read_excel('../input/voter_enrollment/richmonded_feb25.xlsx')
queens_voters_25 = pd.read_excel('../input/voter_enrollment/queensed_feb25.xlsx')
manhatt_voters_25 = pd.read_excel('../input/voter_enrollment/new-yorked_feb25.xlsx')
brooklyn_voters_25 = pd.read_excel('../input/voter_enrollment/kingsed_feb25.xlsx')

In [46]:
## read in voter files
staten_22 = pd.read_excel("../input/voter_enrollment/richmonded_nov22.xlsx", dtype = {"ed": "str"})
bronx_22 = pd.read_excel("../input/voter_enrollment/bronxed_nov22.xlsx", dtype = {"ed": "str"})
kings_22 = pd.read_excel("../input/voter_enrollment/kingsed_nov22.xlsx", dtype = {"ed": "str"})
manhatt_22 = pd.read_excel("../input/voter_enrollment/newyorked_nov22.xlsx", dtype = {"ed": "str"})
queens_22 = pd.read_excel("../input/voter_enrollment/queensed_nov22.xlsx", dtype = {"ed": "str"})

In [60]:
## read in voter files
staten_21 = pd.read_excel("../input/voter_enrollment/richmonded_nov21.xlsx", dtype = {"ed": "str"})
bronx_21 = pd.read_excel("../input/voter_enrollment/bronxed_nov21.xlsx", dtype = {"ed": "str"})
kings_21 = pd.read_excel("../input/voter_enrollment/kingsed_nov21.xlsx", dtype = {"ed": "str"})
manhatt_21 = pd.read_excel("../input/voter_enrollment/newyorked_nov21.xlsx", dtype = {"ed": "str"})
queens_21 = pd.read_excel("../input/voter_enrollment/queensed_nov21.xlsx", dtype = {"ed": "str"})

In [40]:
## import the elections csv that we made in the previous notebook
elections_df = pd.read_csv('../output/elections/elections.csv')

In [34]:
## import crosswalk
ed_cd_crosswalk = gpd.read_file("../input/crosswalks/cd23_ed25_crosswalk.geojson")

## Find Latest Enrollment Counts
The February 2025 voter enrollment data was, at the time of publishing, the latest count of enrolled voters that we had.

In [19]:
## clean staten
drop_staten_rows = staten_voters_25.drop([0,1,2]) # <-- drop the first three rows
reset_staten = drop_staten_rows.reset_index(drop = True) # <-- reset the index so it doesn't start at '3'
reset_staten.columns = reset_staten.iloc[0] # <-- set the first row as the column headers
staten_headers = reset_staten[1:] # <-- drop first row, it's a dupe of the header
reset_staten_again = staten_headers.reset_index(drop = True) # <-- reset the index again
no_staten_nulls = reset_staten_again.dropna(subset = 'COUNTY')
staten_filtered = no_staten_nulls[no_staten_nulls['COUNTY'] == 'Richmond']

In [20]:
## clean bronx
drop_bronx_rows = bronx_voters_25.drop([0,1,2]) # <-- drop the first three rows
reset_bronx = drop_bronx_rows.reset_index(drop = True) # <-- reset the index so it doesn't start at '3'
reset_bronx.columns = reset_bronx.iloc[0] # <-- set the first row as the column headers
bronx_headers = reset_bronx[1:] # <-- drop first row, it's a dupe of the header
reset_bronx_again = bronx_headers.reset_index(drop = True) # <-- reset the index again
no_bronx_nulls = reset_bronx_again.dropna(subset = 'COUNTY')
bronx_filtered = no_bronx_nulls[no_bronx_nulls['COUNTY'] == 'Bronx']

In [21]:
## clean brooklyn
drop_bk_rows = brooklyn_voters_25.drop([0,1,2]) # <-- drop the first three rows
reset_bk = drop_bk_rows.reset_index(drop = True) # <-- reset the index so it doesn't start at '3'
reset_bk.columns = reset_bk.iloc[0] # <-- set the first row as the column headers
bk_headers = reset_bk[1:] # <-- drop first row, it's a dupe of the header
reset_bk_again = bk_headers.reset_index(drop = True) # <-- reset the index again
no_bk_nulls = reset_bk_again.dropna(subset = 'COUNTY')
bk_filtered = no_bk_nulls[no_bk_nulls['COUNTY'] == 'Kings']

In [22]:
## clean queens
drop_queens_rows = queens_voters_25.drop([0,1,2]) # <-- drop the first three rows
reset_queens = drop_queens_rows.reset_index(drop = True) # <-- reset the index so it doesn't start at '3'
reset_queens.columns = reset_queens.iloc[0] # <-- set the first row as the column headers
queens_headers = reset_queens[1:] # <-- drop first row, it's a dupe of the header
reset_queens_again = queens_headers.reset_index(drop = True) # <-- reset the index again
no_queens_nulls = reset_queens_again.dropna(subset = 'COUNTY')
queens_filtered = no_queens_nulls[no_queens_nulls['COUNTY'] == 'Queens']

In [23]:
## clean manhattan
drop_man_rows = manhatt_voters_25.drop([0,1,2]) # <-- drop the first three rows
reset_man = drop_man_rows.reset_index(drop = True) # <-- reset the index so it doesn't start at '3'
reset_man.columns = reset_man.iloc[0] # <-- set the first row as the column headers
man_headers = reset_man[1:] # <-- drop first row, it's a dupe of the header
reset_man_again = man_headers.reset_index(drop = True) # <-- reset the index again
no_man_nulls = reset_man_again.dropna(subset = 'COUNTY')
man_filtered = no_man_nulls[no_man_nulls['COUNTY'] == 'New York']

In [31]:
## concat them all together
counties = [man_filtered,queens_filtered,bronx_filtered,bk_filtered,staten_filtered] # <-- create list of cleaned dfs
registered_25 = pd.concat(counties, ignore_index=True) # <-- combine

In [32]:
## make headers lowercase
registered_25.columns = registered_25.columns.str.lower()

In [73]:
## make a column for the AD/EDs in the new enrollment df
registered_25['ad_ed'] = registered_25['election dist'].str.extract(r'(\d{5})$')

In [37]:
## create new column that combines third parties
registered_25['third_parties'] = registered_25['con'] + registered_25['wor'] + registered_25['oth']

In [38]:
## make a column for the AD/EDs in the new enrollment df
registered_25['ad_ed'] = registered_25['election dist'].str.extract(r'(\d{5})$')

In [43]:
## change name of total column so we don't get confused when combining with other dfs
registered_25 = registered_25.rename(columns={'total':'total_reg_25'})

## Find 2022 Enrollment Counts
We find 2022 enrollment counts by county as of November 2022 in order to find the voter turnout for the gubernatorial election.

In [47]:
## clean staten
drop_staten_rows_22 = staten_22.drop([0,1,2]) # <-- drop the first three rows
reset_staten_22 = drop_staten_rows_22.reset_index(drop = True) # <-- reset the index so it doesn't start at '3'
reset_staten_22.columns = reset_staten_22.iloc[0] # <-- set the first row as the column headers
staten_headers_22 = reset_staten_22[1:] # <-- drop first row, it's a dupe of the header
reset_staten_again_22 = staten_headers_22.reset_index(drop = True) # <-- reset the index again
no_staten_nulls_22 = reset_staten_again_22.dropna(subset = 'COUNTY')
staten_filtered_22 = no_staten_nulls_22[no_staten_nulls_22['COUNTY'] == 'Richmond']

In [48]:
## clean bronx
drop_bronx_rows_22 = bronx_22.drop([0,1,2]) # <-- drop the first three rows
reset_bronx_22 = drop_bronx_rows_22.reset_index(drop = True) # <-- reset the index so it doesn't start at '3'
reset_bronx_22.columns = reset_bronx_22.iloc[0] # <-- set the first row as the column headers
bronx_headers_22 = reset_bronx_22[1:] # <-- drop first row, it's a dupe of the header
reset_bronx_again_22 = bronx_headers_22.reset_index(drop = True) # <-- reset the index again
no_bronx_nulls_22 = reset_bronx_again_22.dropna(subset = 'COUNTY')
bronx_filtered_22 = no_bronx_nulls_22[no_bronx_nulls_22['COUNTY'] == 'Bronx']

In [49]:
## clean brooklyn
drop_bk_rows_22 = kings_22.drop([0,1,2]) # <-- drop the first three rows
reset_bk_22 = drop_bk_rows_22.reset_index(drop = True) # <-- reset the index so it doesn't start at '3'
reset_bk_22.columns = reset_bk_22.iloc[0] # <-- set the first row as the column headers
bk_headers_22 = reset_bk_22[1:] # <-- drop first row, it's a dupe of the header
reset_bk_again_22 = bk_headers_22.reset_index(drop = True) # <-- reset the index again
no_bk_nulls_22 = reset_bk_again_22.dropna(subset = 'COUNTY')
bk_filtered_22 = no_bk_nulls_22[no_bk_nulls_22['COUNTY'] == 'Kings']

In [50]:
## clean queens
drop_queens_rows_22 = queens_22.drop([0,1,2]) # <-- drop the first three rows
reset_queens_22 = drop_queens_rows_22.reset_index(drop = True) # <-- reset the index so it doesn't start at '3'
reset_queens_22.columns = reset_queens_22.iloc[0] # <-- set the first row as the column headers
queens_headers_22 = reset_queens_22[1:] # <-- drop first row, it's a dupe of the header
reset_queens_again_22 = queens_headers_22.reset_index(drop = True) # <-- reset the index again
no_queens_nulls_22 = reset_queens_again_22.dropna(subset = 'COUNTY')
queens_filtered_22 = no_queens_nulls_22[no_queens_nulls_22['COUNTY'] == 'Queens']

In [51]:
## clean manhattan
drop_man_rows_22 = manhatt_22.drop([0,1,2]) # <-- drop the first three rows
reset_man_22 = drop_man_rows_22.reset_index(drop = True) # <-- reset the index so it doesn't start at '3'
reset_man_22.columns = reset_man_22.iloc[0] # <-- set the first row as the column headers
man_headers_22 = reset_man_22[1:] # <-- drop first row, it's a dupe of the header
reset_man_again_22 = man_headers_22.reset_index(drop = True) # <-- reset the index again
no_man_nulls_22 = reset_man_again_22.dropna(subset = 'COUNTY')
man_filtered_22 = no_man_nulls_22[no_man_nulls_22['COUNTY'] == 'New York']

In [52]:
## concat them all together
counties_22 = [man_filtered_22,queens_filtered_22,bronx_filtered_22,bk_filtered_22,staten_filtered_22] # <-- create list of cleaned dfs
registered_22 = pd.concat(counties_22, ignore_index=True) # <-- combine

In [54]:
## make headers lowercase
registered_22.columns = registered_22.columns.str.lower()

In [55]:
## make a column for the AD/EDs in the new enrollment df
registered_22['ad_ed'] = registered_22['election dist'].str.extract(r'(\d{5})$')

In [ ]:
## create a new column for the gov race turnout
registered_22['gov_turnout'] = elections_df['tot_gov_votes']/registered_22['total']

In [61]:
registered_22.head()

,county,election dist,status,dem,rep,con,wor,oth,blank,total,ad_ed,gov_turnout
0,New York,New York 61060,Total,1106,273,6,2,46,553,1986,61060,0.573515
1,New York,New York 61061,Total,912,251,3,2,52,489,1709,61061,0.625512
2,New York,New York 61062,Total,822,216,5,3,39,434,1519,61062,0.21659
3,New York,New York 61063,Total,702,167,3,0,32,393,1297,61063,0.79414
4,New York,New York 61064,Total,1172,282,6,2,72,492,2026,61064,0.535538

## Find 2021 Enrollment Counts

In [62]:
## clean staten
drop_staten_rows_21 = staten_21.drop([0,1,2]) # <-- drop the first three rows
reset_staten_21 = drop_staten_rows_21.reset_index(drop = True) # <-- reset the index so it doesn't start at '3'
reset_staten_21.columns = reset_staten_21.iloc[0] # <-- set the first row as the column headers
staten_headers_21 = reset_staten_21[1:] # <-- drop first row, it's a dupe of the header
reset_staten_again_21 = staten_headers_21.reset_index(drop = True) # <-- reset the index again
no_staten_nulls_21 = reset_staten_again_21.dropna(subset = 'COUNTY')
staten_filtered_21 = no_staten_nulls_21[no_staten_nulls_21['COUNTY'] == 'Richmond']

In [63]:
## clean bronx
drop_bronx_rows_21 = bronx_21.drop([0,1,2]) # <-- drop the first three rows
reset_bronx_21 = drop_bronx_rows_21.reset_index(drop = True) # <-- reset the index so it doesn't start at '3'
reset_bronx_21.columns = reset_bronx_21.iloc[0] # <-- set the first row as the column headers
bronx_headers_21 = reset_bronx_21[1:] # <-- drop first row, it's a dupe of the header
reset_bronx_again_21 = bronx_headers_21.reset_index(drop = True) # <-- reset the index again
no_bronx_nulls_21 = reset_bronx_again_21.dropna(subset = 'COUNTY')
bronx_filtered_21 = no_bronx_nulls_21[no_bronx_nulls_21['COUNTY'] == 'Bronx']

In [64]:
## clean brooklyn
drop_bk_rows_21 = kings_21.drop([0,1,2]) # <-- drop the first three rows
reset_bk_21 = drop_bk_rows_21.reset_index(drop = True) # <-- reset the index so it doesn't start at '3'
reset_bk_21.columns = reset_bk_21.iloc[0] # <-- set the first row as the column headers
bk_headers_21 = reset_bk_21[1:] # <-- drop first row, it's a dupe of the header
reset_bk_again_21 = bk_headers_21.reset_index(drop = True) # <-- reset the index again
no_bk_nulls_21 = reset_bk_again_21.dropna(subset = 'COUNTY')
bk_filtered_21 = no_bk_nulls_21[no_bk_nulls_21['COUNTY'] == 'Kings']

In [65]:
## clean queens
drop_queens_rows_21 = queens_21.drop([0,1,2]) # <-- drop the first three rows
reset_queens_21 = drop_queens_rows_21.reset_index(drop = True) # <-- reset the index so it doesn't start at '3'
reset_queens_21.columns = reset_queens_21.iloc[0] # <-- set the first row as the column headers
queens_headers_21 = reset_queens_21[1:] # <-- drop first row, it's a dupe of the header
reset_queens_again_21 = queens_headers_21.reset_index(drop = True) # <-- reset the index again
no_queens_nulls_21 = reset_queens_again_21.dropna(subset = 'COUNTY')
queens_filtered_21 = no_queens_nulls_21[no_queens_nulls_21['COUNTY'] == 'Queens']

In [66]:
## clean manhattan
drop_man_rows_21 = manhatt_21.drop([0,1,2]) # <-- drop the first three rows
reset_man_21 = drop_man_rows_21.reset_index(drop = True) # <-- reset the index so it doesn't start at '3'
reset_man_21.columns = reset_man_21.iloc[0] # <-- set the first row as the column headers
man_headers_21 = reset_man_21[1:] # <-- drop first row, it's a dupe of the header
reset_man_again_21 = man_headers_21.reset_index(drop = True) # <-- reset the index again
no_man_nulls_21 = reset_man_again_21.dropna(subset = 'COUNTY')
man_filtered_21 = no_man_nulls_21[no_man_nulls_21['COUNTY'] == 'New York']

In [67]:
## concat them all together
counties_21 = [man_filtered_21,queens_filtered_21,bronx_filtered_21,bk_filtered_21,staten_filtered_21] # <-- create list of cleaned dfs
registered_21 = pd.concat(counties_21, ignore_index=True) # <-- combine

In [68]:
## make headers lowercase
registered_21.columns = registered_21.columns.str.lower()

In [69]:
## make a column for the AD/EDs in the new enrollment df
registered_21['ad_ed'] = registered_21['election dist'].str.extract(r'(\d{5})$')

In [71]:
## create a new column for the gov race turnout
registered_21['mayor_turnout'] = elections_df['tot_mayor_votes']/registered_21['total']

## Combine

In [77]:
elections_filtered = elections_df.loc[:,['ad_ed',
                                     'harris',
                                     'trump',
                                     'sliwa',
                                     'adams',
                                     'zeldin',
                                     'hochul']]

In [89]:
elections_filtered['ad_ed'] = elections_filtered['ad_ed'].astype('str')

In [91]:
elections_w_reg_25 = pd.merge(elections_filtered,
                              registered_25[['ad_ed','dem','rep','blank','third_parties']],
                              on='ad_ed',
                              how='left')

In [97]:
elections_w_reg_25

,ad_ed,harris,trump,sliwa,adams,zeldin,hochul,dem,rep,blank,third_parties
0,23001,295.0,1011.0,469.0,107.0,918.0,213.0,539,736,302,131
1,23002,289.0,957.0,499.0,106.0,877.0,186.0,592,689,315,121
2,23003,99.0,330.0,475.0,78.0,252.0,74.0,212,204,139,31
3,23004,391.0,871.0,66.0,27.0,738.0,288.0,677,631,376,68
4,23005,336.0,936.0,311.0,135.0,829.0,250.0,700,624,313,65
...,...,...,...,...,...,...,...,...,...,...,...
4414,87055,485.0,186.0,23.0,115.0,71.0,261.0,NaN,NaN,NaN,NaN
4415,87056,5.0,3.0,22.0,99.0,0.0,2.0,NaN,NaN,NaN,NaN
4416,87057,0.0,0.0,29.0,154.0,NaN,NaN,NaN,NaN,NaN,NaN
4417,87058,NaN,NaN,11.0,112.0,0.0,0.0,NaN,NaN,NaN,NaN
4418,87059,0.0,0.0,19.0,93.0,NaN,NaN,NaN,NaN,NaN,NaN